"""empty message

Revision ID: 669e0c353a30
Revises: 0ec7801e5495
Create Date: 2018-03-26 21:40:52.682863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669e0c353a30'
down_revision = '0ec7801e5495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
